import Head from "next/head";
import React from "react";
import Footer from "../common/Footer";
import Header from "../common/Header";
import Sidebar from "../common/Sidebar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Avalle - NFT Portfolio NEXT Js Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/icons/logo-icon.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header />
      <Sidebar />
      {children}
      <Footer />
    </>
  );
}
