import Head from "next/head";
import React from "react";
import Banner3 from "../components/banner/Banner3";
import Blog3 from "../components/blog/Blog3";
import LatestCollection2 from "../components/collection/LatestCollection2";
import Footer from "../components/common/Footer";
import Sidebar from "../components/common/Sidebar";
import Faq from "../components/faq/Faq";
import Feature1 from "../components/feature/Feature1";
import Header2 from "../components/header/Header2";
import Investor from "../components/investor/Investor";
import Roadmap3 from "../components/roadmap/Roadmap3";
import Testimonial3 from "../components/testimonial/Testimonial3";
import WhyChooseUs2 from "../components/why-choose/WhyChooseUs2";

export default function HomePgae3() {
  return (
    <>
      <Head>
        <title>Avalle - NFT Portfolio NEXT Js Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/icons/logo-icon.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header2 />
      <Sidebar />
      <Banner3 />
      <Feature1 />
      <WhyChooseUs2 />
      <LatestCollection2 />
      <Investor />
      <Roadmap3 />
      <Testimonial3 />
      <Faq />
      <Blog3 />
      <Footer />
    </>
  );
}
