import Head from "next/head";
import React from "react";
import Banner2 from "../components/banner/Banner2";
import Blog2 from "../components/blog/Blog2";
import Collection2 from "../components/collection/Collection2";
import LatestCollection from "../components/collection/LatestCollection";
import Footer from "../components/common/Footer";
import Sidebar from "../components/common/Sidebar";
import Contact2 from "../components/contact/Contact2";
import Counter1 from "../components/counter/Counter1";
import Feature2 from "../components/feature/Feature2";
import Header2 from "../components/header/Header2";
import Roadmap2 from "../components/roadmap/Roadmap2";
import Testimonial2 from "../components/testimonial/Testimonial2";

export default function HomePage2() {
  return (
    <>
      <Head>
        <title>Avalle - NFT Portfolio NEXT Js Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="assets/images/icons/logo-icon.svg"
          type="image/gif"
          sizes="20x20"
        />
      </Head>
      <Header2 />
      <Sidebar />
      <Banner2 />
      <Collection2 />
      <Counter1 />
      <Feature2 />
      <LatestCollection />
      <Testimonial2 />
      <Roadmap2 />
      <Contact2 />
      <Blog2 />
      <Footer />
    </>
  );
}
